### ISSUE TITLE
Interpolation and instance error:  /q.sc.ss01

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Montserrat#12]
/q.sc.ss01

@moyogo 

There seems to be a lingering issue with the outline structure of
 /q.sc.ss01  in Montserrat-Black. 

![q sc ss01](https://user-images.githubusercontent.com/6576107/76989504-dadae200-691c-11ea-9b2d-9faf6ab10f82.png)

@m4rc1e

**Comment by pichotta** [comment]
when is this activated?  /q.sc.ss01.BRACKET.170

when resolved please bash build.sh and sync

**Comment by moyogo** [comment]
I have a fix.

**Comment by moyogo** [comment]
We need to use the [processing attribute](https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#attributes-12) in the designspace rules. I’m rebuilding the fonts and will push a branch for the fix.

**Comment by pichotta** [comment]
Is there a new pull request for this fix?
