### ISSUE TITLE
Outlines:  rendering /U in Thin Italic

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Montserrat#13]
@moyogo 

Looking at the binary files for the Thin Italic.  If the OTFs or TTFs are opened in RF3 this one glyph outline for /U becomes distorted.  The VF.ttf seems to render okay.

![Montserrat Thin _U](https://user-images.githubusercontent.com/6576107/76994294-889dbf00-6924-11ea-8b07-40a6535170b2.png)

**Comment by djrrb** [comment]
I did a bit of testing on this yesterday...seems to happen whether or not I generate from Glyphs or UFO, and even if I change the start point of the outline. Do we think this is a fontmake bug?

**Comment by pichotta** [comment]
@djrrb @moyogo 

Redrawing the /U and /Uogonek looks like it resolved this issue. It may have been the result of a switchback stroke used in joining the accent.
