### ISSUE TITLE
Kerning:  Diff results

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Montserrat#15]
@moyogo 
I left the diff and fb reports in the commit for evaluation. See for example the Black report.html
/T.ss01 and /r

![Black r before](https://user-images.githubusercontent.com/6576107/77711746-3144c200-6fa8-11ea-8664-8fc5f5e36c63.png)

![Black r after](https://user-images.githubusercontent.com/6576107/77711750-343fb280-6fa8-11ea-8522-969da8b34d9b.png)

@m4rc1e
Is there a particular kern issue in the Montserrat that you would like investigated?

**Comment by m4rc1e** [comment]
I've spotted some kerns which overlap.

![montserrat_kern](https://user-images.githubusercontent.com/7525512/77767455-00609d80-7039-11ea-8061-ae59f41fcdef.gif)
