### ISSUE TITLE
Anchor Names: _underscores

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Montserrat#4]
@djrrb 
based on feedback from another family, is the recommendation to rename the anchors so they do not have an _underscore in the anchor name?

if so, can we script this change?   note here that there is already an anchor named 'top' so the ability to rename the anchor vs. remove the underscore in the name is necessary.

![underscore 2019-11-21 at 10 01 55 AM](https://user-images.githubusercontent.com/6576107/69349911-9da06500-0c46-11ea-8fae-6746f0a7c647.png)

**Comment by djrrb** [comment]
Want to get confirmation from marc, but I think it would only be in
noncombining characters (_top, _bottom, etc are valid in comb glyphs I
believe).

Yes it would be scriptable.

**Comment by pichotta** [comment]
@djrrb 
has this issue been addressed with findGlyphsWithUnderscoreAnchors?

**Comment by djrrb** [comment]
running this script should resolve the issue, yes!
